version: "3.9"
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/helpdesk
      - JWT_SECRET=devsecret
      - PORT=4000
      - WORKER_URL=http://worker:8000
      - SEED=true
      - AUTOCLOSE_CONFIDENCE=0.8
    depends_on:
      - mongo
      - worker
    ports:
      - "4000:4000"

  worker:
    build: ./worker
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://localhost:4000
    depends_on:
      - backend

volumes:
  mongo_data:
